# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    tags:
      - 'v*'

jobs:
  create:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.create.outputs.upload_url }}
    steps:
      - name: create release
        id: create
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
  build:
    needs: create
    strategy:
      matrix:
        os: [ macos, ubuntu, windows ]
    runs-on: ${{ matrix.os }}-latest

    steps:

      - uses: actions/checkout@v3

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: dart analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      - name: Run tests
        run: dart test

      - name: compile
        shell: bash
        run: |
          export NAME=ldclblx_${{ github.ref_name }}_${{ matrix.os }}
          mkdir $NAME
          dart compile exe bin/ldclblx.dart -o $NAME/ldclblx
          cp README.md $NAME
      
      - name: zip bash
        if: matrix.os != 'windows'
        run: |
          export NAME=ldclblx_${{ github.ref_name }}_${{ matrix.os }}
          zip -r $NAME.zip $NAME

      - name: zip powershell
        if: matrix.os == 'windows'
        run: Compress-Archive -Path ldclblx_${{ github.ref_name }}_windows/* -Destination ldclblx_${{ github.ref_name }}_windows.zip

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.url }}
          asset_path: ./ldclblx_${{ github.ref_name }}_${{ matrix.os }}.zip
          asset_name: ldclblx_${{ github.ref_name }}_${{ matrix.os }}.zip
          asset_content_type: application/zip